language: python
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"  # nightly build
  # PyPy versions
  - "pypy"  # PyPy2 2.5.0
  - "pypy3" # Pypy3 2.4.0
env:
  - WITH_TQDM="YES"
  - WITH_TQDM="NO"
before_install:
  - pip install coverage codecov
  - test "${WITH_TQDM}" = "YES" && pip install tqdm || echo "Test without tqdm"
script:
  - coverage run --parallel-mode --concurrency=multiprocessing test_parmap.py
  - coverage combine
  - coverage report
after_success:
  - codecov

