name: Continuous Integration

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1 1/3 *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip tox tox-gh-actions
    - name: Test with tox
      run: tox
    - name: Upload coverage.xml
      if: ${{ matrix.python-version == '3.11' }}
      uses: actions/upload-artifact@v3
      with:
        name: tox-gh-actions-coverage
        path: coverage.xml
        if-no-files-found: error
    - name: Upload coverage.xml to codecov
      if: ${{ matrix.python-version == '3.11' }}
      uses: codecov/codecov-action@v3
